questions/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'questions'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^questions/(?P<pk>[0-9]+)/$', views.QuestionView.as_view(), name='question'),
    url(r'^questions/ask/$', views.AskView.as_view(), name='ask'),
    url(r'^questions/(?P<pk>[0-9]+)/answer/$', views.AddAnswer.as_view(), name='answer'),
    url(r'^questions/(?P<q_pk>[0-9]+)/(?P<pk>[0-9]+)/delete/$', views.AnswerDeleteView.as_view(), name='answer_delete'),
    url(r'^questions/(?P<q_pk>[0-9]+)/(?P<pk>[0-9]+)/edit/$', views.AnswerEditView.as_view(), name='answer_edit'),
    url(r'^questions/(?P<q_pk>[0-9]+)/(?P<pk>[0-9]+)/accept/$', views.accept_answer, name='answer_accept'),
    url(r'^questions/(?P<pk>[0-9]+)/delete/$', views.QuestionDeleteView.as_view(), name='question_delete'),
    url(r'^questions/(?P<pk>[0-9]+)/edit/$', views.QuestionEditView.as_view(), name='question_edit'),
    url(r'^questions/tagged/(?P<tag>[\w\s\(\)]+)/$', views.TaggedView.as_view(), name='tagged'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserView.as_view(), name='user'),
    url(r'^users/(?P<pk>[0-9]+)/edit/$', views.UserEditView.as_view(), name='user_edit'),
    url(r'^users/(?P<pk>[0-9]+)/settings/$', views.AccountSettings.as_view(), name='user_settings'),
    url(r'^register/$', views.register, name='register')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stackoverflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from stackoverflow.forms import CustomAuthForm

auth_views.LoginView.authentication_form = CustomAuthForm

urlpatterns = [
    url(r'^', include('questions.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='questions:index'), name='logout')
]

questions/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ClearableFileInput
from django.contrib.auth.models import User

from .models import Answer, UserProfile, Question, Tag

class CustomClearableFileInput(ClearableFileInput):
    template_name = 'custom_clearable_file_input.html'


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text']

class RegisterForm(UserCreationForm):
    
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ('username', 'email')

class QuestionAskForm(forms.ModelForm):
    tags = forms.CharField()
    class Meta:
        model = Question
        fields = ('title', 'text')
    
    def __init__(self, *args, **kwargs):
        super(QuestionAskForm, self).__init__(*args, **kwargs)
        self.fields['tags'].required = False

    def clean_tags(self):
        """
            Tags string to array with whitespace verification
        """
        tags_string = self.cleaned_data['tags'].strip()
        if tags_string == '':
            self.tags = None
            return

        tags_array = tags_string.split(',')

        # Removes whitespaces for every tag
        tags = [t.strip() for t in tags_array]
        self.tags = []
        for t in tags:
            if t == '':
                continue

            # Checks if tag exists and creates it if not
            try:
                filtered = Tag.objects.get(name__exact=t)
                self.tags.append(filtered)
            except Tag.DoesNotExist:
                self.tags.append(Tag.objects.create(name=t))

    def save(self, commit=True):
        question = super(QuestionAskForm, self).save(commit=commit)
        if self.tags is not None:
            for t in self.tags:
                question.tags.add(t)
        return question

class QuestionEditForm(QuestionAskForm):
    def __init__(self, *args, **kwargs):
        super(QuestionEditForm, self).__init__(*args, **kwargs)
        # Coverting tags queryset to string to set CharField's initial value
        tags_array = [t.name for t in kwargs['instance'].tags.all()]
        self.fields['tags'].initial = ', '.join(tags_array)

    def save(self, commit=True):
        question = super(QuestionEditForm, self).save(commit=commit)
        question.tags.clear()
        if self.tags is not None:
            for t in self.tags:
                question.tags.add(t)
        return question

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'description', 'location', 'links')
        widgets = {
            'avatar': CustomClearableFileInput
        }

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')

class EmailChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(EmailChangeForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(EmailChangeForm, self).clean()
        if cleaned_data['email'] == self.instance.email:
            self.add_error('email', 'This is your current email.')
        return cleaned_data

questions/views.py
from django.shortcuts import render, redirect, reverse, Http404, get_object_or_404
from django.conf import settings
from django.utils import timezone
from django.views import generic
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User, AnonymousUser
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.postgres.search import SearchVector, SearchQuery

from .multiform import MultiFormsView
from .models import Question, UserProfile, Answer
from .forms import AnswerForm, RegisterForm, ProfileUpdateForm, UserUpdateForm, EmailChangeForm, QuestionEditForm

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'questions/index.html'
    context_object_name = 'questions'

    def get_queryset(self):
        return Question.objects.order_by('-creation_time')

class QuestionView(generic.DetailView):
    template_name = 'questions/question.html'
    model = Question

    def get_queryset(self):
        return Question.objects.filter(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(QuestionView, self).get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        context['answers'] = list(Answer.objects.filter(question=self.kwargs['pk'], is_accepted=True)) + \
                            list(Answer.objects.filter(question=self.kwargs['pk'], is_accepted=False).order_by('-creation_time'))
        context['form'] = AnswerForm
        return context

class UserView(generic.DetailView):
    template_name = 'questions/user.html'
    context_object_name = 'profile'
    model = User

    def get_queryset(self):
        return User.objects.filter(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(UserView, self).get_context_data(**kwargs)
        context['form'] = ProfileUpdateForm
        user = User.objects.get(pk=self.kwargs['pk'])
        context['created_questions'] = Question.objects.filter(owner=user).order_by('-creation_time')[:5]
        context['posted_answers'] = Answer.objects.filter(owner=user).order_by('-creation_time')[:5]
        return context

class UserEditView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = UserProfile
    template_name_suffix = '_edit'
    login_url = '/'
    redirect_field_name = None
    form_class = ProfileUpdateForm

    # https://stackoverflow.com/questions/15497693/django-can-class-based-views-accept-two-forms-at-a-time/15499249#15499249
    second_form_class = UserUpdateForm

    def get_context_data(self, **kwargs):
        context = super(UserEditView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            initial = {
                'username': context['user'].username,
                'first_name': context['user'].first_name,
                'last_name': context['user'].last_name
            }
            context['form2'] = self.second_form_class(initial=initial)
        return context

    def form_invalid(self, **kwargs):
        return self.render_to_response(self.get_context_data(**kwargs))

    def test_func(self):
        return self.request.user == User.objects.get(pk=self.kwargs['pk'])

    def get_form(self, form_class=None):
        form = super(UserEditView, self).get_form(form_class)
        form.fields['description'].required = False
        form.fields['location'].required = False
        form.fields['links'].required = False
        return form

    def get_second_form(self, second_form_class=None):
        return super(UserEditView, self).get_form(second_form_class)

    def get_success_url(self):
        return '/users/%i' % self.request.user.id

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = self.get_form(self.form_class)
        form2 = self.get_second_form(self.second_form_class)
        form2.instance = self.object.user

        fields = [f for f in form.fields]
        fields += [f for f in form2.fields]

        if form2.is_valid():
            self.form_valid(form2)
        else:
            return self.form_invalid(**{'form2': form2})

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(**{'form': form})

def account_settings(request, **kwargs):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('questions:user', user.id)
        else:
            messages.error(request, 'Something went wrong.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'questions/user_settings.html', {'form': form})

class AccountSettings(LoginRequiredMixin, UserPassesTestMixin, MultiFormsView):
    template_name = 'questions/user_settings.html'
    form_classes = {
        'change_password': PasswordChangeForm,
        'change_email': EmailChangeForm
    }

    def test_func(self):
        return self.request.user == User.objects.get(pk=self.kwargs['pk'])

    def get_change_email_initial(self):
        return {'email': self.request.user.email}

    def create_change_password_form(self, **kwargs):
        return PasswordChangeForm(self.request.user, **kwargs)

    def create_change_email_form(self, **kwargs):
        return EmailChangeForm(instance=self.request.user, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AccountSettings, self).get_context_data(**kwargs)
        return context

    def change_email_form_valid(self, form):
        print(form.__dict__)
        messages.success(self.request, "Email changed")
        user = form.save()
        print(user.email)
        print(settings.EMAIL_HOST_USER)
        ''' 
        To enable sending emails, uncoment email settings in settings.py and fill in credentials in email_credentials.py.
        Using smtp.gmail.com requires turning on less secure apps: https://www.google.com/settings/security/lesssecureapps

        send_mail('Subject', 'Message', settings.EMAIL_HOST_USER, [user.email])
        '''
        return redirect('questions:user_settings', self.request.user.id)

    def change_password_form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        messages.success(self.request, "Password changed.")
        return redirect('questions:user_settings', user.id)

def register(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect(reverse('questions:index'))
    return render(request, 'questions/register.html', {'register_form': form})

class AddAnswer(LoginRequiredMixin, generic.CreateView):
    model = Answer
    fields = ['text']
    login_url = '/login'
    redirect_field_name = None

    def get(self, request, *args, **kwargs):
        raise Http404

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.creation_time = timezone.now()
        form.instance.question = Question.objects.get(pk=self.kwargs['pk'])
        return super(AddAnswer, self).form_valid(form)

class AskView(LoginRequiredMixin, generic.CreateView):
    model = Question
    fields = ['title', 'text', 'tags']
    template_name = 'questions/ask.html'
    login_url = '/login'
    redirect_field_name = None

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.creation_time = timezone.now()
        return super(AskView, self).form_valid(form)

class QuestionDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Question
    success_url = '/'
    login_url = '/'
    redirect_field_name = None

    def test_func(self):
        return self.request.user == Question.objects.get(pk=self.kwargs['pk']).owner

class QuestionEditView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    # model = Question
    # fields = ['title', 'text', 'tags']
    form_class = QuestionEditForm
    template_name_suffix = '_edit'
    login_url = '/'
    redirect_field_name = 'title'

    def get_queryset(self):
        return Question.objects.filter(pk=self.kwargs['pk'])

    def test_func(self):
        return self.request.user == Question.objects.get(pk=self.kwargs['pk']).owner

class AnswerDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Answer
    success_url = ''
    login_url = '/'
    redirect_field_name = None

    def get_success_url(self):
        return reverse('questions:question', args=(self.object.question.id,))

    def test_func(self):
        return self.request.user == Answer.objects.get(pk=self.kwargs['pk']).owner

class AnswerEditView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Answer
    fields = ['text']
    template_name_suffix = '_edit'
    login_url = '/'
    redirect_field_name = None

    def test_func(self):
        return self.request.user == Answer.objects.get(pk=self.kwargs['pk']).owner

@login_required
def accept_answer(request, *args, **kwargs):
    # Requires fetch/ajax in template
    # if not request.method == "POST":
    #     raise Http404

questions/templates/questions/answer_confirm_delete.html
{% extends "base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/forms.css' %}">
    <title>{{ answer.question.title }}</title>
    <style>
        textarea {
            resize: vertical;
            height: 150px;
        }
    </style>
{% endblock head %}

{% block left %}
    <form method="post">
        <h2 class="form-title">Are you sure you want to delete this answer?</h2>
        {% csrf_token %}
        <div class="form-field">
            <strong>Question:</strong><p>{{ answer.question }}</p>
        </div>
        <div class="form-field">
            <strong>Text:</strong><textarea readonly>{{ answer.text }}</textarea>
        </div>
        <div class="form-field">
            <strong>Author: </strong><p><a href="{% url 'questions:user' answer.owner.id %}">{{ answer.owner.username }}</a></p>
        </div>
        <div class="form-field">
            <button type="submit">Confirm</button>
            <a href="{% url 'questions:question' answer.question.id %}">Cancel</a>  
        </div>
    </form>
{% endblock left %}

questions/templates/questions/answer_edit.html
{% extends "base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/forms.css' %}">
    <title>{{ answer.question.title }}</title>
{% endblock head %}

{% block left %}
    <form method="post">
        <h2 class="form-title">Edit answer</h2>
        {% csrf_token %}
        {% for field in form %}
            <div class='form-field'>{{ field.label_tag }}{{ field }}</div>
        {% endfor %}
        <div class="form-field">
            <button type="submit">Confirm</button>
            <a href="{% url 'questions:question' answer.question.id %}">Cancel</a>
        </div>
    </form>
{% endblock left %}

questions/templates/questions/ask.html
{% extends "base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/forms.css' %}">
    <title>Ask Question</title>
{% endblock head %}

{% block left %}

<form method="post">
    <h2 class="form-title">Ask Question</h2>
    {% csrf_token %}
    {% for field in form %}
        <div class="form-field">{{ field.errors }}{{ field.label_tag }}{{ field }}</div>
    {% endfor %}
    <div class='form-field'>
        <button type="submit">Submit</button>
    </div>
</form>
{% endblock left %}

questions/templates/questions/index.html
{% extends "base.html" %}
{% block head %} 
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/index.css' %}">
    <title>Stackoverflow</title>
{% endblock head %} 

{% block left %}
    <div class="menu">
    </div>
    {% if questions %}
    <div id="questions">
        {% for q in questions %}
        <div class="question">
            <div class="question-content">
                <a href="{% url 'questions:question' q.id %}" class='question-title'>
                    {{ q.title }}
                </a>
                <p>{{ q.text|truncatechars:180 }}</p>
                <div class="question-data">
                    <div class="creation-time">
                        {{ q.creation_time }}
                    </div>
                    <div class='owner'>
                        <a href="{% url 'questions:user' q.owner.id %}"><img class='avatar' src="{{ MEDIA_URL }}{{ q.owner.userprofile.avatar }}" alt='avatar' /></a>
                        <a href="{% url 'questions:user' q.owner.id %}" class="username">{{ q.owner }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>There is nothing here. Add some questions!</p>
    {% endif %}
{% endblock left %}

questions/templates/questions/question.html
{% extends "base.html" %} 

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/question.css' %}">
    <link rel="stylesheet" href="{% static 'questions/forms.css' %}">
    <title>{% if question %}{{ question.title }}{% endif %}</title>
{% endblock head %}

{% block content %}
<div class="left">
    {% if question %}
    <div class="question">
        {% if user.id == question.owner.id %}
            <div class="question-options">
                <a href="{% url 'questions:question_delete' question.id %}" class="delete-question" ><i class="fa fa-close fa-2x"></i></a>
                <a href="{% url 'questions:question_edit' question.id %}" class="edit-question"><i class="fa fa-edit fa-2x"></i></a>
            </div>
        {% endif %}
        <div class="question-side">

        </div>
        <div class="question-content">
            <div class="question-header">
                <a class="question-title" href="{% url 'questions:question' question.id %}" class='question-title'>{{ question.title }}</a>
            </div>
            <p class="question-text">{{ question.text }}</p>
            <div class="TesT">
                <div class="question-data">
                    {% if question.tags %}
                        <div class="question-tags">
                            {% for t in question.tags.all %}
                                <a class='tag' href="{% url 'questions:tagged' t.name %}">{{ t }}</a>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div class="creation-time">
                        {{ question.creation_time }}
                    </div>
                    <div class='owner'>
                        <a href="{% url 'questions:user' question.owner.id %}"><img class='avatar' src='{{ MEDIA_URL }}{{ question.owner.userprofile.avatar }}' alt='avatar' /></a>
                        <a href="{% url 'questions:user' question.owner.id %}" class="username">{{ question.owner }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %} 
    <div class="answers">
        <h4>{{ answers.count }} Answer{{ answers.count|pluralize }}</h4>
        {% for answer in answers %}
        <div class="answer" id="{{ answer.id }}">
            {% if user.id == answer.owner.id %}
                <div class="answer-options">
                    <a href="{% url 'questions:answer_delete' answer.question.id answer.id %}" class="delete-answer" ><i class="fa fa-close fa-2x"></i></a>
                    <a href="{% url 'questions:answer_edit' answer.question.id answer.id %}" class="edit-answer"><i class="fa fa-edit fa-2x"></i></a>
                </div>
            {% endif %}
            <div class="answer-side">
                {% if answer.is_accepted %}
                    <span class="accepted-answer"><i class="fa fa-check fa-3x" aria-hidden="true"></i></span>
                {% endif %}

                {% if user.id == question.owner.id and not answer.is_accepted %}
                    <a href="{% url 'questions:answer_accept' question.id answer.id %}" class="accept-answer"><i class="fa fa-check fa-3x" aria-hidden="true"></i></a>
                {% endif %}
            </div>
            <div class="answer-content">
                <p class="answer-text">{{ answer.text }}</p>
                <div class="answer-data">
                    <div class="creation-time">
                        {{ answer.creation_time }}
                    </div>
                    <div class='owner'>
                        <a href="{% url 'questions:user' answer.owner.id %}"><img class='avatar' src='{{ MEDIA_URL }}{{ answer.owner.userprofile.avatar }}' alt='avatar' /></a>
                        <a href="{% url 'questions:user' answer.owner.id %}" class="username">{{ answer.owner }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="message">
                <p>There are no answers right now. Be first!</p>
            </div>
        {% endfor %}
    </div>
    <div class="answer-form">
        <form action='answer/' method="POST">
            <h2 class="form-title">Post your answer</h2>
            {% if not user.is_authenticated %}
                <h3 class='form-subtitle'>You must log in to post an answer</h3>
            {% endif %}
            {% csrf_token %}
            {% for field in form %}
                <div class="form-field">{{ field.label_tag }}{{ field }}</div>
            {% endfor %}
            <div class="form-field">
                <button type="submit">Post Answer</button>
            </div>
        </form>
    </div>
</div>
<div class="right">
    <a id="ask-button" class="outline-button" href="{% url 'questions:ask' %}">Ask Question</a>
</div>
{% endblock content %}

questions/templates/questions/question_confirm_delete.html
{% extends "base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/forms.css' %}">
    <title>{{ question.title }}</title>
    <style>
        textarea {
            resize: vertical;
            height: 150px;
        }
    </style>
{% endblock head %}

{% block left %}
    <form method="post">
        <h2 class="form-title">Are you sure you want to delete this question?</h2>
        {% csrf_token %}
        <div class="form-field">
            <strong>Title:</strong><input type="text" readonly value="{{ question.title }}" />
        </div>
        <div class="form-field">
            <strong>Text:</strong><textarea readonly>{{ question.text }}</textarea>
        </div>
        <div class="form-field">
            <strong>Tags: </strong>
            {% if question.tags.all %}
                {% for t in question.tags.all %}
                    <a class="tag" href="{% url 'questions:tagged' t.name %}">{{ t }}</a>
                {% endfor %}
            {% else %}
                <p>None</p>
            {% endif %}
        </div>
        <div class="form-field">
            <strong>Author: </strong><p><a href="{% url 'questions:user' question.owner.id %}">{{ question.owner.username }}</a></p>
        </div>
        <div class="form-field">
            <button type="submit">Confirm</button>
            <a href="{% url 'questions:question' question.id %}">Cancel</a>  
        </div>
    </form>
{% endblock left %}

questions/templates/questions/question_edit.html
{% extends "base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/forms.css' %}">
    <title>{{ question.title }}</title>
{% endblock head %}

{% block left %}
    <form method="post">
        <h2 class="form-title">Edit question</h2>
        {% csrf_token %}
        {% for field in form %}
            <div class='form-field'>{{ field.label_tag }}{{ field }}</div>
        {% endfor %}
        <div class="form-field">
            <button type="submit">Confirm</button>
            <a href="{% url 'questions:question' question.id %}">Cancel</a>
        </div>
    </form>
{% endblock left %}

questions/templates/questions/register.html
{% extends "base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/forms.css' %}">
    <style>
        form {
            margin-top: 20px !important;
        }

        .form-field {
            width: 400px !important;
        }
      
        .form-field input {
            width: 390px !important;
        }
    </style>
    <title>Sign Up</title>
{% endblock head %}

{% block content %}
    <div class="left">
        <form method="post">
            <h2 class="form-title">Sign Up</h2>
            {% csrf_token %}
            {% for field in register_form %}
                <div class="form-field">
                    {{ field.label_tag }}{{ field }}{{ field.errors }}
                </div>
            {% endfor %}
            <div class="form-field">
                <button type="submit">Sign Up</button>
            </div>
        </form>
        <p>You can also <a href="{% url 'login' %}">log in</a> as guest.</p>
    </div>
    <div class="right">
        <div class="form-messages">
            {% for field in register_form %}
                {% if field.help_text %}
                    <div class="form-message">
                        {{ field.label_tag }}
                        <p>{{ field.help_text|safe }}</p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

questions/templates/questions/user.html
{% extends "base.html" %}


{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/user.css' %}">
    <title>{{ profile.username }}</title>
{% endblock head %}


{% block left %}
    <div class="avatar-container">
        <img class="avatar" src="{{ MEDIA_URL }}{{ profile.userprofile.avatar.name }}" alt="avatar" />
    </div>
    <div class="profile-data">
        <h1 class='username'>
            {{ profile.username }}
        </h1>
        {% if profile.first_name or profile.last_name %}
            <h3 class='name'>{{ profile.first_name }} {{ profile.last_name }}</h3>
        {% endif %}
        {% if profile.userprofile.description %}
            <p class="profile-description">{{ profile.userprofile.description }}</p>
        {% endif %}
    </div>
    {% if user == profile %}
        <a class="edit-profile" href="{% url 'questions:user_edit' profile.id %}">Edit profile</a>
        <a class="edit-profile" href="{% url 'questions:user_settings' profile.id %}">Account settings</a>
    {% endif %}
    <div class="questions section" style="clear: both;">
        <h3 class="section-title">Recent questions:</h3>
        {% for q in created_questions %}
        <div class="question">
            <div class="question-side"></div>
            <div class="question-content">
                <a href="{% url 'questions:question' q.id %}" class='question-title'>
                    {{ q.title }}
                </a>
                <div class="creation-time">
                    {{ q.creation_time }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="answers section">
        <h3 class="section-title">Recent answers:</h3>
        {% for answer in posted_answers %}
        <div class="answer">
            <div class="answer-side">
                {% if answer.is_accepted %}
                    <span class="accepted-answer"><i class="fa fa-check fa-2x" aria-hidden="true"></i></span>
                {% endif %}
            </div>
            <div class="answer-content">
                <a href="{% url 'questions:question' answer.question.id %}#{{ answer.id }}" class='question-title'>
                    {{ answer.question.title }}
                </a>
                <div class="creation-time">
                    {{ answer.creation_time }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock left %}

{% block right %}
    <div class="profile-details">
        <div class="profile-stats">
            <div class="stat-container">
                <h3 class="stat-title">{{ created_questions.count }}</h3>
                <div class="stat-subtitle">question{{ created_questions.count|pluralize }}</div>
            </div>
            <div class="stat-container">
                <h3 class="stat-title">{{ posted_answers.count }}</h3>
                <div class="stat-subtitle">answer{{ posted_answers.count|pluralize }}</div>
            </div>
        </div>
        <ul class="profile-info">
            {% if profile.userprofile.location %}
                <li>Location: {{ profile.userprofile.location }}</li>
            {% endif %}
            {% for link in profile.userprofile.links %}
                <li><a href="{{ link }}">{{ link }}</a></li>
            {% endfor %}
            <li>Member since {{ profile.date_joined|date:"d M Y" }}</li>
            <li>Last seen {{ profile.last_login|date:"d M Y, h:ia" }}</li>
        </ul>
    </div>
{% endblock right %}

{% block ask_button %}{% endblock ask_button %}